### ISSUE TITLE
Update to attributes table on token page

### ISSUE THREAD

**Issue by rorygeoghegan** [reservoirprotocol/marketplace#272]

**Comment by lingzizheng** [comment]
Update the attributes chips UI on token page.

![Image](https://user-images.githubusercontent.com/33438546/169910974-534676fa-f3bd-4718-9382-56df50e1e25a.png)

1. Attribute chips will be ordered from highest floor price to lowest. 
2. See chips component in the figma design for UI edge case.


**Figma Design:**
https://www.figma.com/file/viovJLYOfUuB6TnW67qF5N/?node-id=1202%3A43593

**Comment by rorygeoghegan** [comment]
- [ ] Cap decimals to max 2
- [ ] If there are not decimals then don't show .0%
![Image](https://user-images.githubusercontent.com/96800113/170584082-fbc174a8-b61e-411f-994a-df4aeadf0c43.png)
