### ISSUE TITLE
Support for deployments based on a "collection set", rather than "community"

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/marketplace#400]

**Comment by diegoramosxyz** [comment]
@ptrwtts @rorygeoghegan I don't know what I need to do to complete this task. Please, provide more details.

**Comment by rorygeoghegan** [comment]
@diegoramosxyz we'll sync on this.

**Comment by rorygeoghegan** [comment]
https://api.reservoir.tools/#/4.%20NFT%20API/postCollectionssetsV1 allows builders to create their own sets of collections without the same limitations as communities. We want to allow builders to create their own community marketplace using collectionsetid as an alternative to the community id. All functionalty we have for community id should work with collectionset id.

- [ ] When configured display collections in collection set in dropdown
- [ ] Filter all tabs on portfolio pages by collections within collection set
