### ISSUE TITLE
[Blocked] Powered by Reservoir

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/marketplace#402]
We should have a very subtle icon somewhere, that when you click on it, explains that the marketplace is powered by Reservoir. This is partially for trust (they can click through to read SECURITY.md), along with raising awareness. It should be something communities _want_ to display. Like a `Intel Inside`. That said, should be removable with a ENV variable.

**Comment by diegoramosxyz** [comment]
@rorygeoghegan Do we have a design for this?

**Comment by rorygeoghegan** [comment]
Not yet. Keep this as blocked for now until we have this.
