### ISSUE TITLE
[UI] Issues and links incorrect on Optimisim & Polygon

### ISSUE THREAD

**Issue by timothycarambat** [reservoirprotocol/marketplace#538]
While understanding that the current support for Optimism and Polygon is limited, we should take efforts to try to generalize all UI elements to work with their associated chain so as new chain support is rolled out, the transition is painless.

Some issues discovered when trying to create a marketplace for an Optimism contract:
1. Marketplace links are incorrect. 
- Looksrare does not support Optimism.
- The links for OS now specify the chain and when not specified assume ETH, which may not always be true.
<img width="607" alt="Screen Shot 2022-10-07 at 2 55 08 PM" src="https://user-images.githubusercontent.com/16845892/194668216-0ce6bc3a-a4c9-4080-ac86-4e4931635c7b.png">
Links in the image above:

- https://looksrare.org/collections/0x9b9f542456ad12796ccb8eb6644f29e3314e68e1/1
- https://opensea.io/assets/ethereum/0x9b9f542456ad12796ccb8eb6644f29e3314e68e1/1- 
- https://etherscan.io/address/0x9b9f542456ad12796ccb8eb6644f29e3314e68e1

2. Support for other marketplaces like [Quix.app](https://qx.app/) (Primary Optimism Marketplace) and showing X2Y2 listings for other chains would be nice to see in the token view.

3. The social URLs for Blockexplorer always assume Ethereum (etherescan.io) where this changes depending on the chain of contract.

4. On the collection page Hero image the API_BASE for non-ethereum chains  at `redirect/currency/${address}/icon/v1` does not return a current image and in this case, we should fallback to something rather than show the 'image missing placeholder'
<img width="714" alt="Screen Shot 2022-10-07 at 2 56 47 PM" src="https://user-images.githubusercontent.com/16845892/194668367-40a5701c-4733-4ec1-916b-6c03876c87e1.png">

**Comment by pedromcunha** [comment]
Thanks for submitting this PR! We're going to spend some time over the next few weeks to polish up the marketplace for polygon (and future proof for additional chain support). Closing out this PR for now.
