### ISSUE TITLE
Hosted Solution Form Issue

### ISSUE THREAD

**Issue by TheGreatAxios** [reservoirprotocol/marketplace#572]
Interested in discussing a hosted solution. Your Google Form does not allow me to submit. 

Thanks! @lunarmayor

**Comment by rorygeoghegan** [comment]
Hi @TheGreatAxios, unfortunately we no longer offer a hosted solution for the marketplace. Here is an easy guide to configure and deploy your own self-hosted marketplace. 
https://docs.reservoir.tools/docs/deploy-a-community-marketplace

**Comment by TheGreatAxios** [comment]
Understood, however;

I'm having trouble deploying my own. 

The indexer Keeps throwing V8 memory allocation errors. 

I cannot tell if the API is part of the indexer or separate. 

Would appreciate any guidance.
