### ISSUE TITLE
[Discussion] Support for universal login with underlying wallet

### ISSUE THREAD

**Issue by pandurand** [reservoirprotocol/marketplace#588]
_Just opening a discussion thread here_

We've been looking at the available solutions. Magic looks like one of the most promising candidates for such a feature. We're scoping testing that out for ourselves in the following fashion:

* "Connect Wallet" becomes "Login" and opens a login modal
* the login modal proposes to "connect a wallet" or "with email"
	* "connect a wallet" opens the rainbowkit modal
	* "connect with email" opens the magic modal
* once connected, the available options in the wallet menu may vary:
	* a regular wallet would have the current options
	* a magic wallet would have an additional option: "profile" to open the in app magic modal.
* Once connected, all actions that require a wallet interaction may be approached slightly differently depending on what kind of connexion the user is using

**Notes:**

* Magic allows a user to connect with their wallet directly, but we're thinking on disabling this option because RainbowKit is better.
* In theory, there may be a way to create a Magic connector for RainbowKit, which is an option to explore, but not guaranteed to make it easier to support, which is why the approach described above might be more appropriate.

@pedromcunha 👇 

1. Have you considered adding support for magic or another provider?
2. If we engage into building that support, do you have any interest in collaborating on this?

**Comment by pedromcunha** [comment]
Hi! This seems really interesting, not sure if it's top priority for us or if we'd want to support it in the official OS repo but I can check with the team. I did the bare minimum research here but seems like there's an open source wagmi magic connector: https://github.com/EveripediaNetwork/wagmi-magic-connector

Presumably all you'd need to do is fork the marketplace, install this new dependency and integrate it into _app.tsx. It would just be another login option in the RainbowKit modal.

**Comment by pedromcunha** [comment]
I see, that's unfortunate. Just spoke with the team given everything we've discussed in this thread and the small amount of research I've done. We're going to hold off on this at least for now until the wagmi-magic-connector package matures a little bit more. Generally we like the idea and think if it could be a straightforward addition that it would fit nicely. If you're willing to get the kinks out of the wagmi-magic-connector then we'll reconsider adding it in, we're just juggling a lot of priorities at the moment.

**Comment by pandurand** [comment]
Makes sense! I'll close this thread for the moment, and we can reassess later when we'll have made some progress on our end.
